prevent
Error occurred during initialization of VM
java.lang.Error: java.lang.reflect.InvocationTargetException
        at java.lang.ClassLoader.initSystemClassLoader(java.base@9-ea/Unknown Source)
        at java.lang.System.initPhase3(java.base@9-ea/Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@9-ea/Unknown Source)
        at java.lang.System.initPhase3(java.base@9-ea/Unknown Source)
Caused by: javax.xml.parsers.FactoryConfigurationError: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
        at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-ea/Unknown Source)
        at javax.xml.parsers.FactoryFinder.find(java.xml@9-ea/Unknown Source)
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(java.xml@9-ea/Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:854)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:778)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:104)
        at com.vividsolutions.jump.workbench.Logger.log(Logger.java:118)
        at com.vividsolutions.jump.workbench.Logger.warn(Logger.java:62)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.toFileURL(PlugInClassLoader.java:127)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.addClassPathToUCP(PlugInClassLoader.java:105)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.<init>(PlugInClassLoader.java:28)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@9-ea/Unknown Source)
        at java.lang.System.initPhase3(java.base@9-ea/Unknown Source)
Caused by: java.lang.RuntimeException: Provider for class javax.xml.parsers.DocumentBuilderFactory cannot be created
        at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-ea/Unknown Source)
        at javax.xml.parsers.FactoryFinder.find(java.xml@9-ea/Unknown Source)
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(java.xml@9-ea/Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:854)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:778)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:104)
        at com.vividsolutions.jump.workbench.Logger.log(Logger.java:118)
        at com.vividsolutions.jump.workbench.Logger.warn(Logger.java:62)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.toFileURL(PlugInClassLoader.java:127)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.addClassPathToUCP(PlugInClassLoader.java:105)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.<init>(PlugInClassLoader.java:28)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@9-ea/Unknown Source)
        at java.lang.System.initPhase3(java.base@9-ea/Unknown Source)
Caused by: java.util.ServiceConfigurationError: javax.xml.parsers.DocumentBuilderFactory: not accessible to module java.xml during VM init
        at java.util.ServiceLoader.fail(java.base@9-ea/Unknown Source)
        at java.util.ServiceLoader.<init>(java.base@9-ea/Unknown Source)
        at java.util.ServiceLoader.load(java.base@9-ea/Unknown Source)
        at javax.xml.parsers.FactoryFinder$1.run(java.xml@9-ea/Unknown Source)
        at java.security.AccessController.doPrivileged(java.base@9-ea/Native Method)
        at javax.xml.parsers.FactoryFinder.findServiceProvider(java.xml@9-ea/Unknown Source)
        at javax.xml.parsers.FactoryFinder.find(java.xml@9-ea/Unknown Source)
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(java.xml@9-ea/Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:854)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:778)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.apache.log4j.Logger.getLogger(Logger.java:104)
        at com.vividsolutions.jump.workbench.Logger.log(Logger.java:118)
        at com.vividsolutions.jump.workbench.Logger.warn(Logger.java:62)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.toFileURL(PlugInClassLoader.java:127)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.addClassPathToUCP(PlugInClassLoader.java:105)
        at com.vividsolutions.jump.workbench.plugin.PlugInClassLoader.<init>(PlugInClassLoader.java:28)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(java.base@9-ea/Native Method)
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.reflect.Constructor.newInstance(java.base@9-ea/Unknown Source)
        at java.lang.ClassLoader.initSystemClassLoader(java.base@9-ea/Unknown Source)
        at java.lang.System.initPhase3(java.base@9-ea/Unknown Source)